version: "3.3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  backend:
    build:
      context: WebServer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db